### ISSUE TITLE
AttributeError: 'gtsam.gtsam.ISAM2Params' object has no attribute 'enableRelinearization'

### ISSUE THREAD

**Issue by Yuea922** [ToniRV/NeRF-SLAM#40]
Traceback (most recent call last):
  File "./examples/slam_demo.py", line 200, in <module>
    run(args)
  File "./examples/slam_demo.py", line 143, in run
    slam_module.spin() # visualizer should be the main spin, but pytorch has a memory bug/leak if threaded...
  File "/home/qzy/1_learn/NeRF-SLAM/./examples/../pipeline/pipeline_module.py", line 88, in spin
    self.initialize_module()
  File "/home/qzy/1_learn/NeRF-SLAM/./examples/../slam/slam_module.py", line 19, in initialize_module
    self.slam = VioSLAM(self.name, self.args, self.device)
  File "/home/qzy/1_learn/NeRF-SLAM/./examples/../slam/vio_slam.py", line 100, in __init__
    self.backend = iSAM2()
  File "/home/qzy/1_learn/NeRF-SLAM/./examples/../solvers/nonlinear_solver.py", line 51, in __init__
    isam_params.enableRelinearization = True
AttributeError: 'gtsam.gtsam.ISAM2Params' object has no attribute 'enableRelinearization'

**Comment by Kashu7100** [comment]
Maybe you can modify it like:

```python
isam_params.setEnableRelinearization(True)
isam_params.setEnablePartialRelinearizationCheck(False)
isam_params.setRelinearizeThreshold(0.1) # TODO
isam_params.setRelinearizeSkip(10)
```
