### ISSUE TITLE
ImportError: /usr/local/lib/python3.8/dist-packages/droid_backends-0.0.0-py3.8-linux-x86_64.egg/lietorch_backends.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at10TensorBase8data_ptrIdEEPT_v

### ISSUE THREAD

**Issue by 1005452649** [ToniRV/NeRF-SLAM#46]
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/linzejun01/linzejun_mutiply_view01/NeRF-SLAM/./examples/../pipeline/pipeline_module.py", line 88, in spin
    self.initialize_module()
  File "/home/user/linzejun01/linzejun_mutiply_view01/NeRF-SLAM/./examples/../gui/gui_module.py", line 19, in initialize_module
    from gui.open3d_gui import Open3dGui
  File "/home/user/linzejun01/linzejun_mutiply_view01/NeRF-SLAM/./examples/../gui/open3d_gui.py", line 4, in <module>
    from fusion.tsdf_fusion import TsdfFusion
  File "/home/user/linzejun01/linzejun_mutiply_view01/NeRF-SLAM/./examples/../fusion/tsdf_fusion.py", line 6, in <module>
    from lietorch import SE3
  File "/usr/local/lib/python3.8/dist-packages/droid_backends-0.0.0-py3.8-linux-x86_64.egg/lietorch/__init__.py", line 2, in <module>
    from .groups import LieGroupParameter, SO3, RxSO3, SE3, Sim3, cat, stack
  File "/usr/local/lib/python3.8/dist-packages/droid_backends-0.0.0-py3.8-linux-x86_64.egg/lietorch/groups.py", line 5, in <module>
    from .group_ops import Exp, Log, Inv, Mul, Adj, AdjT, Jinv, Act3, Act4, ToMatrix, ToVec, FromVec
  File "/usr/local/lib/python3.8/dist-packages/droid_backends-0.0.0-py3.8-linux-x86_64.egg/lietorch/group_ops.py", line 1, in <module>
    import lietorch_backends
ImportError: /usr/local/lib/python3.8/dist-packages/droid_backends-0.0.0-py3.8-linux-x86_64.egg/lietorch_backends.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at10TensorBase8data_ptrIdEEPT_v
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/linzejun01/linzejun_mutiply_view01/NeRF-SLAM/./examples/../pipeline/pipeline_module.py", line 88, in spin
    self.initialize_module()
  File "/home/user/linzejun01/linzejun_mutiply_view01/NeRF-SLAM/./examples/../fusion/fusion_module.py", line 21, in initialize_module
    from fusion.tsdf_fusion import TsdfFusion
  File "/home/user/linzejun01/linzejun_mutiply_view01/NeRF-SLAM/./examples/../fusion/tsdf_fusion.py", line 6, in <module>
    from lietorch import SE3
  File "/usr/local/lib/python3.8/dist-packages/droid_backends-0.0.0-py3.8-linux-x86_64.egg/lietorch/__init__.py", line 2, in <module>
    from .groups import LieGroupParameter, SO3, RxSO3, SE3, Sim3, cat, stack
  File "/usr/local/lib/python3.8/dist-packages/droid_backends-0.0.0-py3.8-linux-x86_64.egg/lietorch/groups.py", line 5, in <module>
    from .group_ops import Exp, Log, Inv, Mul, Adj, AdjT, Jinv, Act3, Act4, ToMatrix, ToVec, FromVec
  File "/usr/local/lib/python3.8/dist-packages/droid_backends-0.0.0-py3.8-linux-x86_64.egg/lietorch/group_ops.py", line 1, in <module>
    import lietorch_backends
ImportError: /usr/local/lib/python3.8/dist-packages/droid_backends-0.0.0-py3.8-linux-x86_64.egg/lietorch_backends.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at10TensorBase8data_ptrIdEEPT_v

**Comment by 1005452649** [comment]
@ToniRV

**Comment by 1005452649** [comment]
have solved this problem myself

**Comment by nowhereman1999** [comment]
> 

Hi,I meet a similar problem with you:
![image](https://user-images.githubusercontent.com/53631206/234455019-c7a7d4ab-65d3-452a-9fe2-cba910733df2.png)
could you please tell me how you solved this error finally?

**Comment by 1005452649** [comment]
Check whether the cuda and pytorch versions match, and then update pytorch to match the cuda version @Hezhexi2002

**Comment by 1005452649** [comment]
but i have meet  problem now 
AttributeError: 'gtsam.gtsam.GaussianFactorGraph' object has no attribute 'optimizeDensely'

**Comment by nowhereman1999** [comment]
> Check whether the cuda and pytorch versions match, and then update pytorch to match the cuda version @Hezhexi2002

![image](https://user-images.githubusercontent.com/53631206/234484374-befaf13a-5048-49aa-8a79-cd24f2d152d0.png)
the verion of my cuda and torch should be matched like the screenshot shown above,but the error still exits

**Comment by 1005452649** [comment]
your cuda version? @Hezhexi2002

**Comment by nowhereman1999** [comment]
> your cuda version? @Hezhexi2002

![image](https://user-images.githubusercontent.com/53631206/234493413-5babbda2-119b-4d22-afcf-080fd15e3608.png)
my cuda version is 11.8 as you can see,so you mean I must reinstall the torch with cu118?

**Comment by nowhereman1999** [comment]
> > your cuda version? @Hezhexi2002
> 
> ![image](https://user-images.githubusercontent.com/53631206/234493413-5babbda2-119b-4d22-afcf-080fd15e3608.png) my cuda version is 11.8 as you can see,so you mean I must reinstall the torch with cu118?

![image](https://user-images.githubusercontent.com/53631206/234525852-219e92a6-8187-4825-9cc4-c0f5f0449344.png)
![image](https://user-images.githubusercontent.com/53631206/234525963-e0b2675c-61d7-4f3d-a089-d4caab0ed975.png)
as you can see,the error still exits after I install the torch exactly match my cuda version,is it related to my gtsam installation but the compilation is completely successful,could you please give me more suggestions?

**Comment by 1005452649** [comment]
must reinstall the torch with cu118

**Comment by nowhereman1999** [comment]
> must reinstall the torch with cu118

But there is no release version of torch with cu118

**Comment by 1005452649** [comment]
reinstall cuda @Hezhexi2002
