### ISSUE TITLE
core dump and no output

### ISSUE THREAD

**Issue by sx123456123** [ToniRV/NeRF-SLAM#55]
![2023-09-05 10-48-25 的屏幕截图](https://github.com/ToniRV/NeRF-SLAM/assets/66521231/41c6636d-7b82-4492-b0ff-b8b18347b8bd)
`(nerf-slam) suixin@suixin-Lenovo-Legion-Y7000-1060:~/NeRF-SLAM$ python ./examples/slam_demo.py --dataset_dir=./datasets/Replica/office0 --dataset_name=nerf --buffer=100 --slam --parallel_run --img_stride=2 --fusion='nerf' --gui
Running with GPUs: 0
Running pipeline in parallel mode.
I0905 10:46:31.425204 5567 pipeline_module.py:85] Module: VioSLAM - Spinning.
I0905 10:46:32.228131 5570 pipeline_module.py:85] Module: nerf - Spinning.
I0905 10:46:32.240257 5569 pipeline_module.py:85] Module: nerf - Spinning.
Process Process-2:
Traceback (most recent call last):
  File "/home/suixin/anaconda3/envs/nerf-slam/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/suixin/anaconda3/envs/nerf-slam/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/suixin/NeRF-SLAM/./examples/../pipeline/pipeline_module.py", line 88, in spin
    self.initialize_module()
  File "/home/suixin/NeRF-SLAM/./examples/../fusion/fusion_module.py", line 24, in initialize_module
    from fusion.nerf_fusion import NerfFusion
  File "/home/suixin/NeRF-SLAM/./examples/../fusion/nerf_fusion.py", line 4, in <module>
    from lietorch import SE3
  File "/home/suixin/anaconda3/envs/nerf-slam/lib/python3.9/site-packages/droid_backends-0.0.0-py3.9-linux-x86_64.egg/lietorch/__init__.py", line 2, in <module>
    from .groups import LieGroupParameter, SO3, RxSO3, SE3, Sim3, cat, stack
  File "/home/suixin/anaconda3/envs/nerf-slam/lib/python3.9/site-packages/droid_backends-0.0.0-py3.9-linux-x86_64.egg/lietorch/groups.py", line 5, in <module>
    from .group_ops import Exp, Log, Inv, Mul, Adj, AdjT, Jinv, Act3, Act4, ToMatrix, ToVec, FromVec
  File "/home/suixin/anaconda3/envs/nerf-slam/lib/python3.9/site-packages/droid_backends-0.0.0-py3.9-linux-x86_64.egg/lietorch/group_ops.py", line 1, in <module>
    import lietorch_backends
ImportError: /home/suixin/anaconda3/envs/nerf-slam/lib/python3.9/site-packages/droid_backends-0.0.0-py3.9-linux-x86_64.egg/lietorch_backends.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEE
段错误 (核心已转储)
(nerf-slam) suixin@suixin-Lenovo-Legion-Y7000-1060:~/NeRF-SLAM$ Loading 1000 images.
  1%|▊                                                                                             | 9/1000 [00:00<00:44, 22.35it/s(((( ((((((100%|███████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:54<00:00, 18.37it/s]Stopping data module!
I0905 10:47:40.097312 5569 pipeline_module.py:45] Module: nerf - Shutting down.
I0905 10:47:40.097432 5569 pipeline_module.py:121] Module: nerf - Successful shutdown.
100%|███████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [01:10<00:00, 18.37it/s]
`

**Comment by rrdongdong** [comment]
Hello, has this problem been solved?
